[workspace]
members = [
    "packages/moodle-wasm-example",
    "packages/operator",
    "packages/ai_bridge",
]

resolver = "3"

[profile.prod]
inherits = "release"
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "z"
